import ollama
import time

start_time = time.time()


#system message to set the context and rules for the model's response
system_prompt = '''You are an emergency analysis assistant.
Return output STRICTLY in this format:

Emergency Category:
Severity Level:
Location:
People Involved:
External Services Required:
Summary:

Rules:
- DO NOT include "Thinking", "Analysis", or explanations
- DO NOT include any extra text
- In the external services required include only upto three services and main 
services keep things specific
- DO NOT describe steps
- If unsure, write "Unknown"
- Output must start directly with "Emergency Category:.'''


user_input = '''There is heavy smoke coming out from the second floor of a residential
 building, and bright orange flames can be seen through the windows. Several people inside
  appear to be shouting for help, while others are rushing down the stairs trying to evacuate
   the building in panic..'''

#output generated by the model
result = ollama.chat(
    model  = 'gemini-3-flash-preview',
    messages=[
        {'role': 'system', 'content': system_prompt},
        {
            'role': 'user',
            'content': user_input
        }
    ]
    
)

print(result.message.content)

end_time = time.time()
print(f"Execution time: {end_time - start_time} seconds")