import ollama
import time
import speech_recognition as sr
import json
import re

voice input functionality
recognizer = sr.Recognizer()

with sr.Microphone() as source:
    recognizer.adjust_for_ambient_noise(source, duration=1)
    print('speak now: ')
    audio = recognizer.listen(source)


start_time = time.time()
text = recognizer.recognize_google(audio)

print(text)




#system message to set the context and rules for the model's response
system_prompt = '''You are an emergency analysis assistant.
given the query about the emergency situation in image form or text, return output STRICTLY in
 valid JSON format:

{
  "category":"",
  "severity":"",
  "location":"",
  "services_required":[],
  "summary":"",
  "confidence_score":""
}
confidence score to tell how much you are confident about your answer

if the user query is about the emergency analysis, return compact json. otherwise 
respond normally in plain text form


Rules:
- DO NOT include "Thinking", "Analysis", or explanations
- DO NOT include any extra text
- In the external services required include only upto three services and main 
services keep things specific
- DO NOT describe steps
- If unsure, write "Unknown"
- Output must start directly with "Emergency Category:.

'''


# user_input = '''A high-rise residential building is engulfed in intense flames , with fire
#  spreading rapidly across multiple floors and thick smoke rising into the air. Several
#   occupants may still be trapped inside, and immediate evacuation along with
#    urgent fire brigade and emergency rescue assistance is required.'''

#output generated by the model
result = ollama.chat(
    model  = 'gemma4:31b-cloud',
    messages=[
        {'role': 'system', 'content': system_prompt},
        {
            'role': 'user',
            'content': text,
            'images': ['burning-shopping-center-mall-with-smoke.jpg']
        }
    ]
    
)

output = result.message.content
print(output)

end_time = time.time()
print(f"Execution time: {end_time - start_time} seconds")

