import ollama
import time
import speech_recognition as sr
import json
import re

# voice input functionality
recognizer = sr.Recognizer()

with sr.Microphone() as source:
    recognizer.adjust_for_ambient_noise(source, duration=1)
    print('speak now: ')
    audio = recognizer.listen(source)


start_time = time.time()
text = recognizer.recognize_google(audio)

print(text)




#system message to set the context and rules for the model's response
system_prompt = '''you are an emergency response assistant. Your task is to analyze the given
emergency situation(text, image, or both) and provide structured information that can help emergency responders
assess the situation and determine the necessary actions. The information you provide should be concise,
 accurate, and relevant to the emergency at hand.

 return the information in a JSON format with the following fields:

  "category":"",
  "severity":"",
  "location":"",
  "people_involved": number of people involved
  "services_required":[],
  "summary":"",
  "confidence_score": number between 0 and 1 representing the confidence level of the information provided

for external services required include only main services.
 

if the user query is not about the emergency analysis, respond normally in plain text form


Rules:
- DO NOT include "Thinking", "Analysis", or explanations
- DO NOT include any extra text
- In the external services required include only upto three services and main 
services keep things specific
- DO NOT describe steps
- If unsure, write "Unknown"


'''


# user_input = '''A high-rise residential building is engulfed in intense flames , with fire
#  spreading rapidly across multiple floors and thick smoke rising into the air. 8 to 10
#   occupants may still be trapped inside, and immediate evacuation along with
#    urgent fire brigade and emergency rescue assistance is required.'''

#output generated by the model
result = ollama.chat(
    model  = 'gemma4:31b-cloud',
    messages=[
        {'role': 'system', 'content': system_prompt},
        {
            'role': 'user',
            'content': text,
            'images': ['fire.jpeg']
        }
    ]
    
)

output = result.message.content

print(output)

end_time = time.time()
print(f"Execution time: {end_time - start_time} seconds")

